# Adjusted from the brilliant Ivan Tustanivsky who developed this for Sentry

name: Compile Plugin
on:
  [workflow_call]

jobs:
  test:
    name: Test UE ${{ matrix.unreal }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        unreal: ['5.2']

    steps:
      - name: Free disk space
        if: ${{ steps.exists.outputs.value == 0 }}
        run: |
          # time df -h
          sudo time swapoff -a
          sudo time rm -f /swapfile
          sudo time rm -rf /usr/local/lib/android
          sudo time rm -rf /usr/share/dotnet
          sudo time rm -rf /usr/share/swift
          sudo time rm -rf /usr/local/.ghcup
          sudo time rm -rf /usr/local/lib/node_modules
          sudo time rm -rf /usr/lib/google-cloud-sdk
          sudo time rm -rf /opt/pipx
          sudo time rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo time apt-get clean
          sudo time rm -rf /var/lib/apt/lists/*
          # time docker rmi $(docker image ls -aq)
          # time du --max-depth=3 --threshold=100M -h /usr /opt /var 2>/dev/null | sort -hr
          df -h

      - name: Start Docker container
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          # We start the container with the user ID of the parent GH action user to avoid permission issues on volume.
          uid=$(id -u) # the GH action user ID
          gid=1000     # the ue4 group in the docker container
          user='gh'
          set -x
          docker run -td \
            --name unreal \
            --volume ${{ github.workspace }}:/workspace \
            --workdir /workspace \
            --user $uid:$gid \
            --env PATH="/home/$user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
            ghcr.io/epicgames/unreal-engine:dev-slim-${{ matrix.unreal }}
          docker logout ghcr.io

          # Chown some paths to the GH user to make UE5 work properly. We can't just chown the whole UnrealEngine or
          # docker would implicitly have to copy it to the container and we would run out of space on the GH runner.
          docker exec --user root unreal bash -c "
            chown -R $uid /home/ue4/UnrealEngine/Engine/Binaries/ThirdParty/Mono/Linux ;
            chown -R $uid /home/ue4/UnrealEngine/Engine/Binaries/ThirdParty/DotNet "

      - name: Setup UE CLI
        run: docker exec unreal bash -c '
          pip3 install --upgrade pip ;
          pip3 install -Iv ue4cli==0.0.54 ;
          ue4 setroot /home/ue4/UnrealEngine '

      - uses: actions/checkout@v3
        with:
          path: checkout

      - name: Build & package ${{ matrix.app }}
        id: package-app
        run: |
          docker exec -w /workspace/checkout/ unreal ue4 package
