name: Package Plugin
on:
  workflow_call:
    inputs:
      plugin_name:
        default: 'testdefault'
        type: string
        required: true
        description: 'Test'

jobs:
  publish-engine-plugin:
    runs-on: ubuntu-latest
    name: 📦 Package Plugin
    steps:
      - uses: actions/checkout@v3
      
      - uses: jossef/action-set-json-field@v2
        with:
          file: "${{ github.event.inputs.plugin_name }}.uplugin"
          field: VersionName
          value: "${{ github.ref_name }}"

      - name: Archive files
        run: |
          zip -r archive.zip . -x LICENSE

      - uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_TOKEN }}
          filename: "archive.zip"
          folderId: ${{ secrets.GDRIVE_FOLDER }}
          name: "${{ github.event.inputs.plugin_name }}-${{ github.ref_name }}.zip"
          overwrite: "true"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "archive.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref }}
          name: "${{ github.ref_name }}"
