name: Package Plugin

on:
  workflow_call:
    inputs:
      plugin_name:
        default: "${{ github.event.repository.name }}"
        type: string

jobs:
  publish-engine-plugin:
    runs-on: ubuntu-latest
    name: 📦 Package Plugin
    steps:
      - uses: actions/checkout@v3

      - uses: jossef/action-set-json-field@v2
        with:
          file: "${{ inputs.plugin_name }}.uplugin"
          field: VersionName
          value: "${{ github.ref_name }}"

      - name: Archive files
        run: |
          zip -r "${{ inputs.plugin_name }}-${{ github.ref_name }}.zip" .

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ inputs.plugin_name }}-${{ github.ref_name }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          tag: ${{ github.ref }}
          name: "${{ github.ref_name }}"